<!DOCTYPE html>
    <html>
    <head>
      <meta charset='utf-8'>
      <meta name='viewport' content='width=device-width'>
      <title><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Política de privacidad</font></font></title>
      <style> body { font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; padding:1em; } </style>
    </head>
    <body>
    <strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Política de privacidad</font></font></strong> <p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
                  [Desarrollador/Nombre de la empresa] creó la aplicación Bot Runner FIA como aplicación [de código abierto/gratis/freemium/con publicidad/comercial]. </font><font style="vertical-align: inherit;">Este SERVICIO es proporcionado por [Desarrollador/Nombre de la empresa] [sin costo] y está diseñado para usarse tal cual.
                </font></font></p> <p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
                  Esta página se utiliza para informar a los visitantes sobre [mis/nuestras] políticas con la recopilación, el uso y la divulgación de información personal si alguien decide utilizar [mi/nuestro] Servicio.
                </font></font></p> <p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
                  Si elige usar [mi/nuestro] Servicio, entonces acepta la recopilación y el uso de información en relación con esta política. </font><font style="vertical-align: inherit;">La información personal que [yo/nosotros] recopilamos se utiliza para proporcionar y mejorar el Servicio. </font><font style="vertical-align: inherit;">[Yo/Nosotros] no usaremos ni compartiremos su información con nadie excepto como se describe en esta Política de privacidad.
                </font></font></p> <p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
                  Los términos utilizados en esta Política de privacidad tienen los mismos significados que en nuestros Términos y condiciones, a los que se puede acceder en Bot Runner FIA a menos que se defina lo contrario en esta Política de privacidad.
                </font></font></p> <p><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Recopilación y uso de información</font></font></strong></p> <p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
                  Para una mejor experiencia, mientras usa nuestro Servicio, [yo/nosotros] podemos solicitarle que nos proporcione cierta información de identificación personal [agregue cualquier otra cosa que recopile aquí, por ejemplo, nombre de usuario, dirección, ubicación, imágenes] La información que [yo/ Nosotros] la solicitud será [retenida en su dispositivo y no será recopilada por [yo/nosotros] de ninguna manera]/[retenida por nosotros y utilizada como se describe en esta política de privacidad].
                </font></font></p> <div><p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
                    La aplicación utiliza servicios de terceros que pueden recopilar información utilizada para identificarlo.
                  </font></font></p> <p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
                    Enlace a la política de privacidad de los proveedores de servicios de terceros utilizados por la aplicación
                  </font></font></p> <ul><li><a href="https://www.google.com/policies/privacy/" target="_blank" rel="noopener noreferrer"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Servicios de Google Play</font></font></a></li><!----><!----><!----><li><a href="https://www.facebook.com/about/privacy/update/printable" target="_blank" rel="noopener noreferrer"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Facebook</font></font></a></li><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----></ul></div> <p><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Dato de registro</font></font></strong></p> <p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
                  [Yo/Nosotros] queremos informarle que siempre que use [mi/nuestro] Servicio, en caso de un error en la aplicación [Yo/Nosotros] recopilamos datos e información (a través de productos de terceros) en su teléfono llamado Registro Datos. </font><font style="vertical-align: inherit;">Estos Datos de registro pueden incluir información como la dirección del Protocolo de Internet ("IP") de su dispositivo, el nombre del dispositivo, la versión del sistema operativo, la configuración de la aplicación cuando utiliza [mi/nuestro] Servicio, la hora y la fecha de su uso del Servicio. , y otras estadísticas.
                </font></font></p> <p><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Galletas</font></font></strong></p> <p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
                  Las cookies son archivos con una pequeña cantidad de datos que se utilizan comúnmente como identificadores únicos anónimos. </font><font style="vertical-align: inherit;">Estos se envían a su navegador desde los sitios web que visita y se almacenan en la memoria interna de su dispositivo.
                </font></font></p> <p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
                  Este Servicio no utiliza estas "cookies" de forma explícita. </font><font style="vertical-align: inherit;">Sin embargo, la aplicación puede usar código y bibliotecas de terceros que usan "cookies" para recopilar información y mejorar sus servicios. </font><font style="vertical-align: inherit;">Tiene la opción de aceptar o rechazar estas cookies y saber cuándo se envía una cookie a su dispositivo. </font><font style="vertical-align: inherit;">Si elige rechazar nuestras cookies, es posible que no pueda utilizar algunas partes de este Servicio.
                </font></font></p> <p><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Proveedores de servicio</font></font></strong></p> <p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
                  [Yo/Nosotros] podemos contratar a empresas e individuos de terceros debido a las siguientes razones:
                </font></font></p> <ul><li><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Para facilitar nuestro Servicio;</font></font></li> <li><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Para proporcionar el Servicio en nuestro nombre;</font></font></li> <li><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Para realizar servicios relacionados con el Servicio; </font><font style="vertical-align: inherit;">o</font></font></li> <li><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Para ayudarnos a analizar cómo se utiliza nuestro Servicio.</font></font></li></ul> <p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
                  [Yo/Nosotros] queremos informar a los usuarios de este Servicio que estos terceros tienen acceso a su Información personal. </font><font style="vertical-align: inherit;">El motivo es realizar las tareas que se les asignan en nuestro nombre. </font><font style="vertical-align: inherit;">Sin embargo, están obligados a no divulgar ni utilizar la información para ningún otro fin.
                </font></font></p> <p><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Seguridad</font></font></strong></p> <p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
                  [Yo/nosotros] valoramos su confianza al proporcionarnos su información personal, por lo que nos esforzamos por utilizar medios comercialmente aceptables para protegerla. </font><font style="vertical-align: inherit;">Pero recuerde que ningún método de transmisión por Internet, o método de almacenamiento electrónico es 100% seguro y confiable, y [Yo/Nosotros] no podemos garantizar su absoluta seguridad.
                </font></font></p> <p><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Enlaces a otros sitios</font></font></strong></p> <p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
                  Este Servicio puede contener enlaces a otros sitios. </font><font style="vertical-align: inherit;">Si hace clic en un enlace de un tercero, será dirigido a ese sitio. </font><font style="vertical-align: inherit;">Tenga en cuenta que estos sitios externos no son operados por [yo/nosotros]. </font><font style="vertical-align: inherit;">Por lo tanto, [yo/nosotros] le recomendamos encarecidamente que revise la Política de privacidad de estos sitios web. </font><font style="vertical-align: inherit;">[Yo/Nosotros] no tenemos control ni asumimos ninguna responsabilidad por el contenido, las políticas de privacidad o las prácticas de los sitios o servicios de terceros.
                </font></font></p> <p><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Privacidad de los niños</font></font></strong></p> <div><p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
                    Estos Servicios no se dirigen a ninguna persona menor de 13 años. [Yo/Nosotros] no recopilamos a sabiendas información de identificación personal de niños menores de 13 años. </font><font style="vertical-align: inherit;">En el caso de que [yo/nosotros] descubramos que un niño menor de 13 años [me/nosotros] nos ha proporcionado información personal, [yo/nosotros] la borramos inmediatamente de nuestros servidores. </font><font style="vertical-align: inherit;">Si usted es un padre o tutor y sabe que su hijo nos ha proporcionado información personal, comuníquese con [mí/nosotros] para que [yo/nosotros] podamos realizar las acciones necesarias.
                  </font></font></p></div> <!----> <p><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Cambios a esta Política de Privacidad</font></font></strong></p> <p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
                  [Yo/Nosotros] podemos actualizar nuestra Política de privacidad de vez en cuando. </font><font style="vertical-align: inherit;">Por lo tanto, se le recomienda revisar esta página periódicamente para ver si hay cambios. </font><font style="vertical-align: inherit;">[Yo/nosotros] le notificaremos cualquier cambio publicando la nueva Política de privacidad en esta página.
                </font></font></p> <p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Esta política es efectiva a partir del 2022-04-08</font></font></p> <p><strong><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Contáctenos</font></font></strong></p> <p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
                  Si tiene alguna pregunta o sugerencia sobre [mi/nuestra] Política de Privacidad, no dude en comunicarse [conmigo/nosotros] a arnold_guerrero1@usmp.pe.
                </font></font></p> <p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Esta página de política de privacidad fue creada en </font></font><a href="https://privacypolicytemplate.net" target="_blank" rel="noopener noreferrer"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">privacypolicytemplate.net</font></font></a><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> y modificada/generada por </font></font><a href="https://app-privacy-policy-generator.nisrulz.com/" target="_blank" rel="noopener noreferrer"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">App Privacy Policy Generator</font></font></a></p>
    </body>
    </html>